// generate.ts — Write context files into a project for the selected AI tool

import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import type { DetectedTech, DetectionResult, Monorepo, PackageManager } from './detect.js';
import type { TargetTool } from './index.js';
import { selectFiles } from './registry.js';

interface GenerateOptions {
  projectDir:    string;
  detection:     DetectionResult;
  tool:          TargetTool;
  includeAgents: boolean;
}

function runPrefixFor(pm: PackageManager): string {
  switch (pm) {
    case 'pnpm': return 'pnpm';
    case 'yarn': return 'yarn';
    case 'bun':  return 'bun run';
    default:     return 'npm run';   // npm, unknown
  }
}

interface GenerateResult {
  fileCount: number;
  files:     string[];
}

// ── package.json helpers (used by AGENTS.md) ───────────────────────

interface PkgJson {
  name?:            string;
  version?:         string;
  scripts?:         Record<string, string>;
  dependencies?:    Record<string, string>;
  devDependencies?: Record<string, string>;
}

function readPkg(projectDir: string): PkgJson | null {
  try {
    return JSON.parse(readFileSync(join(projectDir, 'package.json'), 'utf-8')) as PkgJson;
  } catch { return null; }
}

function stripSemver(v: string): string {
  return v.replace(/^[\^~><=\s]+/, '').trim();
}

// ── Claude Code ────────────────────────────────────────────────────

function generateClaudeMd(detected: DetectedTech[], skillPaths: string[]): string {
  const skillNames = skillPaths
    .filter(p => p.includes('skills/'))
    .map(p => p.split('skills/')[1].split('/')[0]);
  const agentNames = skillPaths
    .filter(p => p.includes('agents/'))
    .map(p => p.split('agents/')[1].replace('.md', ''));

  const stackLine = detected.length > 0 ? detected.join(', ') : 'generic project';

  return `# Project: Claude Code Context

> Read this file fully before writing any code.
> Skills in \`.claude/skills/\` load automatically when relevant.
> Agents in \`.claude/agents/\` are available for specialized tasks.

## Project Overview

**Detected stack:** ${stackLine}

<!--
  Fill in the sections below to give Claude more context about your project.
  The more detail you add, the better Claude Code performs.
-->

## Architecture

<!-- Describe how the system is structured (frontend, backend, services, DB) -->

## Data Model

<!-- Key entities and their relationships -->

## Conventions

<!-- Project-specific coding conventions, naming, folder structure -->

## Available Skills
${skillNames.length > 0
    ? skillNames.map(n => `- \`${n}\``).join('\n')
    : '- (none detected — add your stack and re-run contextengine)'}

## Available Agents
${agentNames.length > 0
    ? agentNames.map(n => `- \`${n}\``).join('\n')
    : '- (none)'}

---

*Generated by [ContextEngine](https://github.com/strifero/ContextEngine) — by [Strife Technologies](https://strifetech.com)*
`;
}

async function generateClaude(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detection, includeAgents } = opts;
  const detected = detection.techs;
  const claudeDir = join(projectDir, '.claude');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detection, includeAgents);

  for (const file of skillFiles) {
    const fullPath = join(claudeDir, file.path);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, file.content, 'utf-8');
    writtenFiles.push(`.claude/${file.path}`);
  }

  const claudeMdPath = join(claudeDir, 'CLAUDE.md');
  if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true });
  writeFileSync(claudeMdPath, generateClaudeMd(detected, skillFiles.map(f => f.path)), 'utf-8');
  writtenFiles.unshift('.claude/CLAUDE.md');

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── Cursor ─────────────────────────────────────────────────────────

function generateCursorRule(tech: string, content: string): string {
  return `---
description: ${tech} best practices and conventions
globs: ["**/*"]
alwaysApply: false
---

${content}
`;
}

async function generateCursor(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detection } = opts;
  const rulesDir = join(projectDir, '.cursor', 'rules');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detection, false);
  for (const file of skillFiles) {
    if (!file.path.includes('skills/')) continue;
    const tech = file.path.split('skills/')[1].split('/')[0];
    const outPath = join(rulesDir, `${tech}.mdc`);
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(outPath, generateCursorRule(tech, file.content), 'utf-8');
    writtenFiles.push(`.cursor/rules/${tech}.mdc`);
  }

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── GitHub Copilot ─────────────────────────────────────────────────

async function generateCopilot(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detection } = opts;
  const detected = detection.techs;
  const githubDir = join(projectDir, '.github');
  const outPath = join(githubDir, 'copilot-instructions.md');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detection, false);
  const stackLine = detected.length > 0 ? detected.join(', ') : 'generic project';

  const sections = skillFiles
    .filter(f => f.path.includes('skills/'))
    .map(f => {
      const tech = f.path.split('skills/')[1].split('/')[0];
      return `## ${tech}\n\n${f.content.trim()}`;
    })
    .join('\n\n---\n\n');

  const content = `# GitHub Copilot Instructions

> Generated by [ContextEngine](https://github.com/strifero/ContextEngine)

## Project Stack

**Detected:** ${stackLine}

## Conventions

<!-- Add project-specific conventions here -->

---

${sections}
`;

  mkdirSync(githubDir, { recursive: true });
  writeFileSync(outPath, content, 'utf-8');
  writtenFiles.push('.github/copilot-instructions.md');

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── AGENTS.md ──────────────────────────────────────────────────────
// Spec: https://agents.md
// One file at the project root, read by Codex, OpenCode, and a growing
// list of agents. We keep Conventions and What-to-avoid summaries
// hardcoded here (not pulled from skills.ts) so the skill prose stays
// the single source of Claude Code's skill library and this file stays
// the single source of AGENTS.md's condensed guidance.

const DISPLAY_NAME: Record<DetectedTech, string> = {
  typescript:    'TypeScript',
  nodejs:        'Node.js',
  express:       'Express',
  'nextjs-app':  'Next.js (App Router)',
  'nextjs-pages':'Next.js (Pages Router)',
  react:         'React',
  vite:       'Vite',
  vue:        'Vue',
  tailwind:   'Tailwind CSS',
  swiftui:    'SwiftUI',
  stripe:     'Stripe',
  prisma:     'Prisma',
  postgresql: 'PostgreSQL',
  mongodb:    'MongoDB',
  azure:      'Azure',
  docker:     'Docker',
  go:         'Go',
  python:     'Python',
  django:     'Django',
  rust:       'Rust',
  bun:        'Bun',
  php:        'PHP',
  csharp:     'C#',
  vitest:         'Vitest',
  jest:           'Jest',
  playwright:     'Playwright',
  cypress:        'Cypress',
  eslint:         'ESLint (legacy config)',
  'eslint-flat':  'ESLint (flat config)',
  biome:          'Biome',
  prettier:       'Prettier',
  astro:          'Astro',
  sveltekit:      'SvelteKit',
  remix:          'Remix',
  nuxt:           'Nuxt',
  nestjs:         'NestJS',
  fastapi:        'FastAPI',
  rails:          'Ruby on Rails',
  laravel:        'Laravel',
};

const TECH_TO_PACKAGE: Partial<Record<DetectedTech, string>> = {
  'nextjs-app':   'next',
  'nextjs-pages': 'next',
  react:          'react',
  typescript:     'typescript',
  vite:           'vite',
  vue:            'vue',
  tailwind:       'tailwindcss',
  express:        'express',
  stripe:         'stripe',
  prisma:         '@prisma/client',
  vitest:         'vitest',
  jest:           'jest',
  playwright:     '@playwright/test',
  cypress:        'cypress',
  astro:          'astro',
  sveltekit:      '@sveltejs/kit',
  remix:          '@remix-run/react',
  nuxt:           'nuxt',
  nestjs:         '@nestjs/core',
};

interface AgentsSummary { conventions: string[]; avoid: string[]; }

const AGENTS_SUMMARY: Record<DetectedTech, AgentsSummary> = {
  typescript: {
    conventions: [
      'Run with `strict: true` in tsconfig. Prefer `interface` for object shapes and `type` for unions.',
      'All async code uses async/await. No raw `.then()` chains in application code.',
      'Files kebab-case, types PascalCase, functions and vars camelCase, constants SCREAMING_SNAKE_CASE.',
    ],
    avoid: [
      'Using `any`. Reach for `unknown` and narrow with type guards.',
      'Type assertions (`as X`) except at boundaries you control.',
    ],
  },
  nodejs: {
    conventions: [
      'ES modules (`"type": "module"`) with explicit `.js` extensions on imports.',
      'Use native fetch where available. Reserve axios for interceptor-heavy flows.',
    ],
    avoid: [
      'Mixing CommonJS and ESM in the same package.',
    ],
  },
  express: {
    conventions: [
      'Validate request bodies with zod before touching business logic.',
      'Centralize error handling in one middleware. API errors return `{ error: string }` with the right HTTP status.',
    ],
    avoid: [
      'Throwing inside route handlers without a surrounding try/catch.',
    ],
  },
  'nextjs-app': {
    conventions: [
      'App Router by default. Server Components unless the file declares `"use client"`.',
      'Database access lives in Server Components, Route Handlers, or Server Actions, never client code.',
      'Route Handlers at `app/<path>/route.ts` export named methods (GET, POST, etc.).',
    ],
    avoid: [
      '`getServerSideProps` and `getStaticProps`. The App Router replaced them.',
      'Importing server-only modules from client components.',
    ],
  },
  'nextjs-pages': {
    conventions: [
      'File-based routing under `pages/`. Each file maps to a route.',
      '`getServerSideProps` for per-request data, `getStaticProps` with `getStaticPaths` for build-time data.',
      'API routes at `pages/api/<name>.ts` export a default handler taking `(req, res)`.',
    ],
    avoid: [
      'App Router conventions (`app/`, Route Handlers, Server Actions) inside `pages/` code.',
      'Mutating state in `getStaticProps`: it runs at build, not per-request.',
    ],
  },
  react: {
    conventions: [
      'Function components and hooks only.',
      'Lift state to the lowest common ancestor. Co-locate state with the component that owns it.',
    ],
    avoid: [
      'Class components in new code.',
      'Derived state in `useState` when it can be computed during render.',
    ],
  },
  vite: {
    conventions: [
      'Environment variables prefixed with `VITE_` to expose to client code.',
      'Reference static assets via `new URL(path, import.meta.url)`.',
    ],
    avoid: [
      'Reading `process.env` directly in client code. Use `import.meta.env`.',
    ],
  },
  vue: {
    conventions: [
      'Composition API with `<script setup>` for new components.',
      'Props typed via `defineProps<...>()`, emits via `defineEmits<...>()`.',
    ],
    avoid: [
      'Options API in new components, unless matching existing files.',
    ],
  },
  tailwind: {
    conventions: [
      'Utility classes in markup. Extract to a component (not `@apply`) when a pattern repeats.',
      'Design tokens live in `tailwind.config.*` under `theme.extend`.',
    ],
    avoid: [
      'Inline `style={{ ... }}` for anything Tailwind already covers.',
    ],
  },
  swiftui: {
    conventions: [
      'One View per file, named after the struct.',
      'State flows down via `@Binding`, up via closures or `@ObservableObject`.',
    ],
    avoid: [
      'UIKit types inside SwiftUI views unless wrapping via `UIViewRepresentable`.',
    ],
  },
  stripe: {
    conventions: [
      'Amounts stored and passed in the smallest currency unit (cents).',
      'Verify webhook signatures with the Stripe SDK before trusting the payload.',
    ],
    avoid: [
      'Calling the Stripe API from client code with a secret key.',
    ],
  },
  prisma: {
    conventions: [
      'Single PrismaClient instance at `lib/prisma.ts`. Import that, never `new PrismaClient()` in request paths.',
      'Schema changes go through `prisma migrate dev` locally and `prisma migrate deploy` in CI.',
    ],
    avoid: [
      '`$executeRawUnsafe` with user input. Use `$executeRaw` tagged templates.',
    ],
  },
  postgresql: {
    conventions: [
      'Parameterize every query. Never string-concatenate user input into SQL.',
      'Index the columns you filter and join on. Run `EXPLAIN ANALYZE` on perf-critical paths.',
    ],
    avoid: [
      '`SELECT *` in application code. List the columns you need.',
    ],
  },
  mongodb: {
    conventions: [
      'Create indexes for every `find` filter your app runs in a hot path.',
      'Validate documents at the application layer or with JSON Schema validators.',
    ],
    avoid: [
      'Unbounded `find()` calls. Always `.limit(...)` or paginate.',
    ],
  },
  azure: {
    conventions: [
      'Managed Identity for service-to-service auth. No connection strings in code.',
      'Resource definitions live in Bicep or Terraform, not the portal.',
    ],
    avoid: [
      'Secrets stored in app settings. Use Key Vault references.',
    ],
  },
  docker: {
    conventions: [
      'Multi-stage builds: compile in a builder image, copy artifacts into a minimal runtime.',
      'Pin base image tags by digest or version. No `latest` in production Dockerfiles.',
    ],
    avoid: [
      'Running containers as root. Add a non-root user in the final stage.',
    ],
  },
  go: {
    conventions: [
      'Return errors as the last value. Wrap with `fmt.Errorf("context: %w", err)` when bubbling up.',
      'Interfaces defined where they are consumed, not where they are implemented.',
    ],
    avoid: [
      'Using `panic` for expected error conditions.',
    ],
  },
  python: {
    conventions: [
      'Type hints on every public function. Run mypy or pyright in CI.',
      'Format with black or ruff-format. Lint with ruff.',
    ],
    avoid: [
      'Bare `except:` clauses. Catch the specific exception.',
    ],
  },
  django: {
    conventions: [
      'Business logic in services, not views or models.',
      '`select_related` for forward FKs, `prefetch_related` for reverse and M2M.',
    ],
    avoid: [
      'N+1 queries. Check with `django-debug-toolbar` or `CaptureQueriesContext`.',
    ],
  },
  rust: {
    conventions: [
      'Return `Result<T, E>` from fallible functions. Reserve panics for invariants that cannot fail.',
      'Use `thiserror` for library error types, `anyhow` at application boundaries.',
    ],
    avoid: [
      'Unnecessary `.clone()` and `.unwrap()` in library code.',
    ],
  },
  bun: {
    conventions: [
      '`bun` as package manager and test runner. `bunx` replaces `npx`.',
      'Bun native APIs (`Bun.file`, `Bun.serve`) where they fit. Fall back to Node APIs for ecosystem compat.',
    ],
    avoid: [
      'Mixing `npm install` and `bun install` in the same repo.',
    ],
  },
  php: {
    conventions: [
      'PSR-12 coding style. Composer for dependencies. PHP 8+ typed properties.',
    ],
    avoid: [
      '`include`/`require` scatter. Use Composer autoloading.',
    ],
  },
  csharp: {
    conventions: [
      'Nullable reference types enabled. `record` for DTOs, `class` for entities with identity.',
    ],
    avoid: [
      'Catching `Exception` broadly. Catch the specific type or rethrow.',
    ],
  },
  vitest: {
    conventions: [
      'Co-locate `<file>.test.ts` next to the module under test.',
      '`vitest run` in CI, `vitest` for watch locally.',
    ],
    avoid: [
      '`vi.useFakeTimers()` without a matching `vi.useRealTimers()` in `afterEach`.',
    ],
  },
  jest: {
    conventions: [
      'Co-locate `<file>.test.ts`. Shared helpers under `__mocks__/` or `__tests__/__helpers__/`.',
      'Reset mocks between tests (`jest.resetAllMocks()` or `resetMocks: true` in config).',
    ],
    avoid: [
      '`jest.mock` inside a test body. It hoists, so declare at top of file.',
    ],
  },
  playwright: {
    conventions: [
      'Role-based selectors (`getByRole`, `getByLabel`) before `getByTestId`. Avoid CSS selectors.',
      'Trust auto-waits. `trace: "retain-on-failure"` so failed runs are debuggable from CI.',
    ],
    avoid: [
      '`page.waitForTimeout`. Assert visibility or wait on a network response.',
    ],
  },
  cypress: {
    conventions: [
      '`data-cy` attributes for selectors. Avoid classes tied to styling.',
      '`cy.intercept` plus `cy.wait("@alias")` for network waits.',
    ],
    avoid: [
      '`cy.wait(<ms>)`. Use command retry or intercept aliases.',
    ],
  },
  eslint: {
    conventions: [
      'Legacy `.eslintrc` config. Run `eslint .` in CI; agents should not introduce new warnings.',
    ],
    avoid: [
      'Disabling rules inline except with a one-line reason comment.',
    ],
  },
  'eslint-flat': {
    conventions: [
      'Flat config (`eslint.config.*`). Run `eslint .` in CI; keep the lint output green.',
    ],
    avoid: [
      'Disabling rules inline except with a one-line reason comment.',
    ],
  },
  biome: {
    conventions: [
      'Biome handles lint and format together. Run `biome check --write` before committing.',
    ],
    avoid: [
      'Mixing Biome with Prettier or ESLint for the same files. Pick one pipeline.',
    ],
  },
  prettier: {
    conventions: [
      'Prettier is the source of truth for formatting. Run `prettier --write` or wire it into the editor.',
    ],
    avoid: [
      'Hand-formatting code that Prettier will rewrite. Configure Prettier instead.',
    ],
  },
  astro: {
    conventions: [
      'Pages under `src/pages/`, layouts under `src/layouts/`, components under `src/components/`.',
      'Server-rendered by default. Add `client:load`, `client:idle`, or `client:visible` only where hydration is needed.',
      'Public env vars prefixed `PUBLIC_` and read via `import.meta.env`.',
    ],
    avoid: [
      'Hydrating whole pages. Push `client:*` directives down to the smallest island.',
    ],
  },
  sveltekit: {
    conventions: [
      'Routes under `src/routes/`. `+page.server.ts` for server-only loads and form actions, `+page.ts` for universal.',
      'API endpoints: `+server.ts` exporting `GET`, `POST`, etc. Return `Response` or use `json()`.',
      'Use `$env/static/private` and `$env/static/public` to keep secrets out of client bundles.',
    ],
    avoid: [
      'Importing server-only code from `+page.svelte` or `+layout.svelte`.',
    ],
  },
  remix: {
    conventions: [
      'Data via `loader` (GET-like) and `action` (form submissions). Both server-only.',
      'Nested routing: parents render `<Outlet />`, children compose in. Loaders run in parallel.',
      'Resource routes (no default export) become API endpoints returning `Response`.',
    ],
    avoid: [
      'Fetching in components. Move to `loader`; return via `useLoaderData()`.',
    ],
  },
  nuxt: {
    conventions: [
      'Pages under `pages/`, API under `server/api/`, composables under `composables/` (auto-imported).',
      'Data fetching with `useFetch` or `useAsyncData` so SSR and client stay aligned.',
      'Runtime config via `useRuntimeConfig()`. Keep secrets out of the `public` sub-object.',
    ],
    avoid: [
      'Calling APIs in `onMounted`. Use `useFetch` and let Nuxt compose data on the server.',
    ],
  },
  nestjs: {
    conventions: [
      'One feature per module: controller + service + DTOs colocated under the same directory.',
      'Validate bodies with `class-validator` DTOs and a global `ValidationPipe`.',
      'Inject dependencies through the constructor. Prefer interface tokens for swappable implementations.',
    ],
    avoid: [
      'Business logic in controllers. Delegate to services; controllers only wire HTTP to service calls.',
    ],
  },
  fastapi: {
    conventions: [
      'Group routes into `APIRouter`s by resource. Mount them from `main.py`.',
      'Pydantic models for request and response shapes. Annotate return types for OpenAPI.',
      '`async def` endpoints. Move CPU work to `run_in_threadpool` so the event loop stays free.',
    ],
    avoid: [
      'Blocking calls (sync DB drivers, `time.sleep`) in `async` endpoints.',
    ],
  },
  rails: {
    conventions: [
      'Skinny controllers, fat models (or services). Strong params declared at the top of the controller.',
      'Manage schema with `bin/rails db:migrate`; one change per migration, reversible where possible.',
      'Use `bundle exec` to run rake / rails tasks inside the project gemset.',
    ],
    avoid: [
      'Business logic in views. Push it to helpers, services, or model methods.',
    ],
  },
  laravel: {
    conventions: [
      'Validate with Form Request classes; keep controllers focused on HTTP.',
      'Schema via migrations (`php artisan make:migration`, `php artisan migrate`). Seed with seeders, not ad-hoc scripts.',
      'Use `php artisan` for every task runner need: migrations, queues, custom commands.',
    ],
    avoid: [
      'Inline validation inside controllers when a Form Request fits.',
    ],
  },
};

// For fastapi, surface the detected Python tool (poetry/uv/pip) as an
// additional Conventions bullet so agents know which tooling is in use.
const PYTHON_TOOL_BULLETS: Record<Exclude<DetectionResult['pythonTool'], null>, string> = {
  poetry: 'Poetry-managed: `poetry install`, `poetry run uvicorn <app>:app --reload`. Deps live in pyproject.toml.',
  uv:     'uv-managed: `uv sync`, `uv run uvicorn <app>:app --reload`. Deps live in pyproject.toml.',
  pip:    'pip-managed: `pip install -r requirements.txt`, then `uvicorn <app>:app --reload`.',
};

// Techs dropped first when AGENTS.md exceeds the 8 KB cap. Order:
// least-specific first, so specific guidance survives truncation.
const TRUNCATION_ORDER: DetectedTech[] = ['typescript', 'nodejs'];

function techWithVersion(tech: DetectedTech, pkg: PkgJson | null): string {
  const name = DISPLAY_NAME[tech];
  const packageName = TECH_TO_PACKAGE[tech];
  if (!packageName || !pkg) return name;
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };
  const raw = deps[packageName];
  if (!raw) return name;
  return `${name} ${stripSemver(raw)}`;
}

function buildStackSection(detected: DetectedTech[], pkg: PkgJson | null): string {
  if (detected.length === 0) return '(no stack detected)';
  return detected.map(t => `- ${techWithVersion(t, pkg)}`).join('\n');
}

// Script names extracted into the Commands section. Prefix match via
// `db:` and `test:` handled separately. Case-insensitive.
const KNOWN_SCRIPT_NAMES = new Set([
  'dev', 'start', 'build',
  'test',
  'lint', 'format',
  'typecheck', 'type-check', 'tsc',
  'migrate', 'seed',
]);

function isKnownScript(name: string): boolean {
  const lower = name.toLowerCase();
  if (KNOWN_SCRIPT_NAMES.has(lower)) return true;
  if (lower.startsWith('test:')) return true;
  if (lower.startsWith('db:')) return true;
  return false;
}

function buildCommandsSection(scripts: Record<string, string>, runPrefix: string): string {
  const entries = Object.entries(scripts).filter(([k]) => isKnownScript(k));
  if (entries.length === 0) return '(no recognized package.json scripts. Fill in the commands agents should run for build, test, lint, etc.)';
  return entries.map(([k, v]) => `- \`${runPrefix} ${k}\`: \`${v}\``).join('\n');
}

function buildSummarySection(techs: DetectedTech[], key: 'conventions' | 'avoid', detection: DetectionResult): string {
  const bullets: string[] = [];
  for (const t of techs) {
    const entry = AGENTS_SUMMARY[t];
    if (!entry) continue;
    for (const line of entry[key]) bullets.push(`- ${line}`);
    // Dynamic: surface detected Python tool in fastapi's conventions.
    if (t === 'fastapi' && key === 'conventions' && detection.pythonTool) {
      bullets.push(`- ${PYTHON_TOOL_BULLETS[detection.pythonTool]}`);
    }
  }
  return bullets.length > 0 ? bullets.join('\n') : '(no stack-specific guidance)';
}

const MONOREPO_DISPLAY: Record<Exclude<Monorepo, null>, string> = {
  'turbo':            'Turbo',
  'nx':               'Nx',
  'pnpm-workspaces':  'pnpm workspaces',
  'lerna':            'Lerna',
  'rush':             'Rush',
};

function buildMonorepoSection(monorepo: Monorepo): string {
  if (!monorepo) return '';
  return `## Monorepo

- ${MONOREPO_DISPLAY[monorepo]} workspace. Packages under \`packages/\` (or as declared in the workspace config).

`;
}

function renderAgentsMd(
  projectName: string,
  detected: DetectedTech[],
  pkg: PkgJson | null,
  summaryTechs: DetectedTech[],
  detection: DetectionResult,
): string {
  const stack       = buildStackSection(detected, pkg);
  const monorepo    = buildMonorepoSection(detection.monorepo);
  const commands    = buildCommandsSection(detection.scripts, runPrefixFor(detection.packageManager));
  const conventions = buildSummarySection(summaryTechs, 'conventions', detection);
  const avoid       = buildSummarySection(summaryTechs, 'avoid', detection);

  return `# ${projectName}

> AGENTS.md: instructions for AI coding agents working on this project.
> Human contributors: see README.md.

## Stack

${stack}

${monorepo}## Commands

${commands}

## Conventions

${conventions}

## What to avoid

${avoid}

---

*Generated by [ContextEngine](https://github.com/strifero/ContextEngine). Re-run to refresh.*
`;
}

function generateAgentsMd(projectDir: string, detection: DetectionResult): string {
  const pkg = readPkg(projectDir);
  const projectName = pkg?.name || basename(projectDir) || 'project';
  const detected = detection.techs;

  let summaryTechs = [...detected];
  let output = renderAgentsMd(projectName, detected, pkg, summaryTechs, detection);

  for (const drop of TRUNCATION_ORDER) {
    if (output.length <= 8192) break;
    summaryTechs = summaryTechs.filter(t => t !== drop);
    output = renderAgentsMd(projectName, detected, pkg, summaryTechs, detection);
  }
  return output;
}

// All targets whose output is the AGENTS.md body at a different path.
// The body is identical across targets: only the file location varies.
// Order here controls the order files are listed in `--tool all` output.
const AGENTS_BODY_TARGETS: ReadonlyArray<{ tool: TargetTool; path: string }> = [
  { tool: 'agents',   path: 'AGENTS.md' },
  { tool: 'windsurf', path: '.windsurfrules' },
  { tool: 'aider',    path: 'CONVENTIONS.md' },
  { tool: 'gemini',   path: 'GEMINI.md' },
  { tool: 'cline',    path: '.clinerules' },
  { tool: 'roo',      path: '.roo/rules.md' },
  { tool: 'junie',    path: '.junie/guidelines.md' },
  { tool: 'amazon-q', path: '.amazonq/rules/project.md' },
  { tool: 'opencode', path: '.opencode/AGENTS.md' },
  { tool: 'zed',      path: '.rules' },
];

async function writeAgentsTarget(opts: GenerateOptions, outputPath: string): Promise<GenerateResult> {
  const { projectDir, detection } = opts;
  const body = generateAgentsMd(projectDir, detection);
  const full = join(projectDir, outputPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body, 'utf-8');
  return { fileCount: 1, files: [outputPath] };
}

// ── Main export ────────────────────────────────────────────────────

export async function generateFiles(opts: GenerateOptions): Promise<GenerateResult> {
  if (opts.tool === 'all') {
    const [claude, cursor, copilot] = await Promise.all([
      generateClaude({  ...opts, tool: 'claude' }),
      generateCursor({  ...opts, tool: 'cursor' }),
      generateCopilot({ ...opts, tool: 'copilot' }),
    ]);
    const bodyResults = await Promise.all(
      AGENTS_BODY_TARGETS.map(t => writeAgentsTarget({ ...opts, tool: t.tool }, t.path)),
    );
    const everything = [claude, cursor, copilot, ...bodyResults];
    return {
      fileCount: everything.reduce((n, r) => n + r.fileCount, 0),
      files:     everything.flatMap(r => r.files),
    };
  }

  if (opts.tool === 'cursor')  return generateCursor(opts);
  if (opts.tool === 'copilot') return generateCopilot(opts);

  const bodyTarget = AGENTS_BODY_TARGETS.find(t => t.tool === opts.tool);
  if (bodyTarget) return writeAgentsTarget(opts, bodyTarget.path);

  return generateClaude(opts);
}
