// generate.ts — Write context files into a project for the selected AI tool

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import type { DetectedTech } from './detect.js';
import type { TargetTool } from './index.js';
import { selectFiles } from './registry.js';

interface GenerateOptions {
  projectDir:    string;
  detected:      DetectedTech[];
  tool:          TargetTool;
  includeAgents: boolean;
}

interface GenerateResult {
  fileCount: number;
  files:     string[];
}

// ── Claude Code ────────────────────────────────────────────────────

function generateClaudeMd(detected: DetectedTech[], skillPaths: string[]): string {
  const skillNames = skillPaths
    .filter(p => p.includes('skills/'))
    .map(p => p.split('skills/')[1].split('/')[0]);
  const agentNames = skillPaths
    .filter(p => p.includes('agents/'))
    .map(p => p.split('agents/')[1].replace('.md', ''));

  const stackLine = detected.length > 0 ? detected.join(', ') : 'generic project';

  return `# Project — Claude Code Context

> Read this file fully before writing any code.
> Skills in \`.claude/skills/\` load automatically when relevant.
> Agents in \`.claude/agents/\` are available for specialized tasks.

## Project Overview

**Detected stack:** ${stackLine}

<!-- 
  Fill in the sections below to give Claude more context about your project.
  The more detail you add, the better Claude Code performs.
-->

## Architecture

<!-- Describe how the system is structured (frontend, backend, services, DB) -->

## Data Model

<!-- Key entities and their relationships -->

## Conventions

<!-- Project-specific coding conventions, naming, folder structure -->

## Available Skills
${skillNames.length > 0
    ? skillNames.map(n => `- \`${n}\``).join('\n')
    : '- (none detected — add your stack and re-run contextengine)'}

## Available Agents
${agentNames.length > 0
    ? agentNames.map(n => `- \`${n}\``).join('\n')
    : '- (none)'}

---

*Generated by [ContextEngine](https://github.com/strifero/ContextEngine) — by [Strife Technologies](https://strifetech.com)*
`;
}

async function generateClaude(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detected, includeAgents } = opts;
  const claudeDir = join(projectDir, '.claude');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detected, includeAgents);

  for (const file of skillFiles) {
    const fullPath = join(claudeDir, file.path);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, file.content, 'utf-8');
    writtenFiles.push(`.claude/${file.path}`);
  }

  const claudeMdPath = join(claudeDir, 'CLAUDE.md');
  if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true });
  writeFileSync(claudeMdPath, generateClaudeMd(detected, skillFiles.map(f => f.path)), 'utf-8');
  writtenFiles.unshift('.claude/CLAUDE.md');

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── Cursor ─────────────────────────────────────────────────────────

function generateCursorRule(tech: string, content: string): string {
  return `---
description: ${tech} best practices and conventions
globs: ["**/*"]
alwaysApply: false
---

${content}
`;
}

async function generateCursor(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detected } = opts;
  const rulesDir = join(projectDir, '.cursor', 'rules');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detected, false);
  for (const file of skillFiles) {
    if (!file.path.includes('skills/')) continue;
    const tech = file.path.split('skills/')[1].split('/')[0];
    const outPath = join(rulesDir, `${tech}.mdc`);
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(outPath, generateCursorRule(tech, file.content), 'utf-8');
    writtenFiles.push(`.cursor/rules/${tech}.mdc`);
  }

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── GitHub Copilot ─────────────────────────────────────────────────

async function generateCopilot(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detected } = opts;
  const githubDir = join(projectDir, '.github');
  const outPath = join(githubDir, 'copilot-instructions.md');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detected, false);
  const stackLine = detected.length > 0 ? detected.join(', ') : 'generic project';

  const sections = skillFiles
    .filter(f => f.path.includes('skills/'))
    .map(f => {
      const tech = f.path.split('skills/')[1].split('/')[0];
      return `## ${tech}\n\n${f.content.trim()}`;
    })
    .join('\n\n---\n\n');

  const content = `# GitHub Copilot Instructions

> Generated by [ContextEngine](https://github.com/strifero/ContextEngine)

## Project Stack

**Detected:** ${stackLine}

## Conventions

<!-- Add project-specific conventions here -->

---

${sections}
`;

  mkdirSync(githubDir, { recursive: true });
  writeFileSync(outPath, content, 'utf-8');
  writtenFiles.push('.github/copilot-instructions.md');

  return { fileCount: writtenFiles.length, files: writtenFiles };
}

// ── Main export ────────────────────────────────────────────────────

export async function generateFiles(opts: GenerateOptions): Promise<GenerateResult> {
  if (opts.tool === 'all') {
    const [claude, cursor, copilot] = await Promise.all([
      generateClaude({ ...opts, tool: 'claude' }),
      generateCursor({ ...opts, tool: 'cursor' }),
      generateCopilot({ ...opts, tool: 'copilot' }),
    ]);
    return {
      fileCount: claude.fileCount + cursor.fileCount + copilot.fileCount,
      files: [...claude.files, ...cursor.files, ...copilot.files],
    };
  }
  if (opts.tool === 'cursor')  return generateCursor(opts);
  if (opts.tool === 'copilot') return generateCopilot(opts);
  return generateClaude(opts);
}
